name: CI/CD Pipeline for Batttrack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Verify installation

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image with Docker Compose
      run: |
        docker-compose -f docker-compose.yml build

    - name: Push to Docker Hub
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: bestbest/batttrack-api:latest

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to host
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p $SERVER_PORT $SERVER_USERNAME@$SERVER_IP << EOF
          docker stop batttrackapi || true
          docker rm batttrackapi || true
          docker-compose -f docker-compose.yml pull
          docker-compose -f docker-compose.yml up -d
        EOF
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        PARTNER_ID: ${{ secrets.PARTNER_ID }}
        PARTNER_KEY: ${{ secrets.PARTNER_KEY }}
        REDIRECT_URL: ${{ secrets.REDIRECT_URL }}
        CODE: ${{ secrets.CODE }}
        SHOP_ID: ${{ secrets.SHOP_ID }}
